# -*- coding: utf-8 -*-
"""Untitled59.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odvpx9NOZCwleT6GAl4ltAJVPoWvs2s-
"""

import pandas as pd

# Load the dataset
file_path = "Refined_Merged_Global_Indicators_Cleaned.csv"
df = pd.read_csv(file_path)

# Remove duplicate rows
df_cleaned = df.drop_duplicates()

# Save the cleaned dataset
cleaned_file_path = "Cleaned_Global_Indicators_No_Duplicates.csv"
df_cleaned.to_csv(cleaned_file_path, index=False)

print(f"Cleaned dataset saved as {cleaned_file_path}")

import pandas as pd

# Load the dataset
file_path = "Refined_Merged_Global_Indicators_Cleaned.csv"
df = pd.read_csv(file_path)

# Remove duplicate rows
df_cleaned = df.drop_duplicates()

# Save the cleaned dataset
cleaned_file_path = "Cleaned_Global_Indicators_No_Duplicates.csv"
df_cleaned.to_csv(cleaned_file_path, index=False)

# Provide the download link
print(f"Download the cleaned file: [Download Here](sandbox:/{cleaned_file_path})")

import pandas as pd
from google.colab import files

# Load the dataset (Make sure you have uploaded it in Colab)
file_path = "Refined_Merged_Global_Indicators_Cleaned.csv"  # Update with your actual file name
df = pd.read_csv(file_path)

# Remove duplicate rows
df_cleaned = df.drop_duplicates()

# Save the cleaned dataset
cleaned_file_path = "Cleaned_Global_Indicators_No_Duplicates.csv"
df_cleaned.to_csv(cleaned_file_path, index=False)

# Download the file
files.download(cleaned_file_path)